package fr.lagab.portlet.publication.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fr.lagab.portlet.publication.model.Publication;
import fr.lagab.portlet.publication.service.PublicationLocalServiceUtil;

/**
 * The extended model base implementation for the Publication service. Represents a row in the &quot;publication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PublicationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PublicationImpl
 * @see fr.lagab.portlet.publication.model.Publication
 * @generated
 */
public abstract class PublicationBaseImpl extends PublicationModelImpl
    implements Publication {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a publication model instance should use the {@link Publication} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PublicationLocalServiceUtil.addPublication(this);
        } else {
            PublicationLocalServiceUtil.updatePublication(this);
        }
    }
}
