package fr.lagab.portlet.publication.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Publication service. Represents a row in the &quot;publication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fr.lagab.portlet.publication.model.impl.PublicationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fr.lagab.portlet.publication.model.impl.PublicationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Publication
 * @see fr.lagab.portlet.publication.model.impl.PublicationImpl
 * @see fr.lagab.portlet.publication.model.impl.PublicationModelImpl
 * @generated
 */
public interface PublicationModel extends BaseModel<Publication>,
    StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a publication model instance should use the {@link Publication} interface instead.
     */

    /**
     * Returns the primary key of this publication.
     *
     * @return the primary key of this publication
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this publication.
     *
     * @param primaryKey the primary key of this publication
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this publication.
     *
     * @return the uuid of this publication
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this publication.
     *
     * @param uuid the uuid of this publication
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the ID of this publication.
     *
     * @return the ID of this publication
     */
    public long getId();

    /**
     * Sets the ID of this publication.
     *
     * @param id the ID of this publication
     */
    public void setId(long id);

    /**
     * Returns the group ID of this publication.
     *
     * @return the group ID of this publication
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this publication.
     *
     * @param groupId the group ID of this publication
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this publication.
     *
     * @return the company ID of this publication
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this publication.
     *
     * @param companyId the company ID of this publication
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this publication.
     *
     * @return the user ID of this publication
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this publication.
     *
     * @param userId the user ID of this publication
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this publication.
     *
     * @return the user uuid of this publication
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this publication.
     *
     * @param userUuid the user uuid of this publication
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this publication.
     *
     * @return the user name of this publication
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this publication.
     *
     * @param userName the user name of this publication
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this publication.
     *
     * @return the create date of this publication
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this publication.
     *
     * @param createDate the create date of this publication
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this publication.
     *
     * @return the modified date of this publication
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this publication.
     *
     * @param modifiedDate the modified date of this publication
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the folder ID of this publication.
     *
     * @return the folder ID of this publication
     */
    public long getFolderId();

    /**
     * Sets the folder ID of this publication.
     *
     * @param folderId the folder ID of this publication
     */
    public void setFolderId(long folderId);

    /**
     * Returns the title of this publication.
     *
     * @return the title of this publication
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this publication.
     *
     * @param title the title of this publication
     */
    public void setTitle(String title);

    /**
     * Returns the url title of this publication.
     *
     * @return the url title of this publication
     */
    @AutoEscape
    public String getUrlTitle();

    /**
     * Sets the url title of this publication.
     *
     * @param urlTitle the url title of this publication
     */
    public void setUrlTitle(String urlTitle);

    /**
     * Returns the description of this publication.
     *
     * @return the description of this publication
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this publication.
     *
     * @param description the description of this publication
     */
    public void setDescription(String description);

    /**
     * Returns the content of this publication.
     *
     * @return the content of this publication
     */
    @AutoEscape
    public String getContent();

    /**
     * Sets the content of this publication.
     *
     * @param content the content of this publication
     */
    public void setContent(String content);

    /**
     * Returns the structure ID of this publication.
     *
     * @return the structure ID of this publication
     */
    public long getStructureId();

    /**
     * Sets the structure ID of this publication.
     *
     * @param structureId the structure ID of this publication
     */
    public void setStructureId(long structureId);

    /**
     * Returns the template ID of this publication.
     *
     * @return the template ID of this publication
     */
    public long getTemplateId();

    /**
     * Sets the template ID of this publication.
     *
     * @param templateId the template ID of this publication
     */
    public void setTemplateId(long templateId);

    /**
     * Returns the status of this publication.
     *
     * @return the status of this publication
     */
    public int getStatus();

    /**
     * Sets the status of this publication.
     *
     * @param status the status of this publication
     */
    public void setStatus(int status);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        fr.lagab.portlet.publication.model.Publication publication);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fr.lagab.portlet.publication.model.Publication> toCacheModel();

    @Override
    public fr.lagab.portlet.publication.model.Publication toEscapedModel();

    @Override
    public fr.lagab.portlet.publication.model.Publication toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
