package fr.lagab.portlet.publication.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.CompanyPersistence;
import com.liferay.portal.service.persistence.GroupPersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.portlet.asset.service.persistence.AssetCategoryPersistence;
import com.liferay.portlet.asset.service.persistence.AssetEntryPersistence;
import com.liferay.portlet.asset.service.persistence.AssetLinkPersistence;
import com.liferay.portlet.asset.service.persistence.AssetTagPersistence;
import com.liferay.portlet.dynamicdatamapping.service.persistence.DDMStructurePersistence;
import com.liferay.portlet.dynamicdatamapping.service.persistence.DDMTemplatePersistence;
import com.liferay.portlet.ratings.service.persistence.RatingsStatsPersistence;
import com.liferay.portlet.social.service.persistence.SocialActivityCounterPersistence;
import com.liferay.portlet.social.service.persistence.SocialActivityPersistence;
import com.liferay.portlet.trash.service.persistence.TrashEntryPersistence;

import fr.lagab.portlet.publication.model.Publication;
import fr.lagab.portlet.publication.service.PublicationService;
import fr.lagab.portlet.publication.service.persistence.PublicationPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the publication remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link fr.lagab.portlet.publication.service.impl.PublicationServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see fr.lagab.portlet.publication.service.impl.PublicationServiceImpl
 * @see fr.lagab.portlet.publication.service.PublicationServiceUtil
 * @generated
 */
public abstract class PublicationServiceBaseImpl extends BaseServiceImpl
    implements PublicationService, IdentifiableBean {
    @BeanReference(type = fr.lagab.portlet.publication.service.PublicationLocalService.class)
    protected fr.lagab.portlet.publication.service.PublicationLocalService publicationLocalService;
    @BeanReference(type = fr.lagab.portlet.publication.service.PublicationService.class)
    protected fr.lagab.portlet.publication.service.PublicationService publicationService;
    @BeanReference(type = PublicationPersistence.class)
    protected PublicationPersistence publicationPersistence;
    @BeanReference(type = fr.lagab.portlet.publication.service.PublicationStructureLocalService.class)
    @SuppressWarnings("deprecation")
    protected fr.lagab.portlet.publication.service.PublicationStructureLocalService publicationStructureLocalService;
    @BeanReference(type = fr.lagab.portlet.publication.service.PublicationStructureService.class)
    @SuppressWarnings("deprecation")
    protected fr.lagab.portlet.publication.service.PublicationStructureService publicationStructureService;
    @BeanReference(type = fr.lagab.portlet.publication.service.PublicationTemplateLocalService.class)
    @SuppressWarnings("deprecation")
    protected fr.lagab.portlet.publication.service.PublicationTemplateLocalService publicationTemplateLocalService;
    @BeanReference(type = fr.lagab.portlet.publication.service.PublicationTemplateService.class)
    @SuppressWarnings("deprecation")
    protected fr.lagab.portlet.publication.service.PublicationTemplateService publicationTemplateService;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.mail.service.MailService.class)
    protected com.liferay.mail.service.MailService mailService;
    @BeanReference(type = com.liferay.portal.service.CompanyLocalService.class)
    protected com.liferay.portal.service.CompanyLocalService companyLocalService;
    @BeanReference(type = com.liferay.portal.service.CompanyService.class)
    protected com.liferay.portal.service.CompanyService companyService;
    @BeanReference(type = CompanyPersistence.class)
    protected CompanyPersistence companyPersistence;
    @BeanReference(type = com.liferay.portal.service.GroupLocalService.class)
    protected com.liferay.portal.service.GroupLocalService groupLocalService;
    @BeanReference(type = com.liferay.portal.service.GroupService.class)
    protected com.liferay.portal.service.GroupService groupService;
    @BeanReference(type = GroupPersistence.class)
    protected GroupPersistence groupPersistence;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    @BeanReference(type = com.liferay.portlet.asset.service.AssetCategoryLocalService.class)
    protected com.liferay.portlet.asset.service.AssetCategoryLocalService assetCategoryLocalService;
    @BeanReference(type = com.liferay.portlet.asset.service.AssetCategoryService.class)
    protected com.liferay.portlet.asset.service.AssetCategoryService assetCategoryService;
    @BeanReference(type = AssetCategoryPersistence.class)
    protected AssetCategoryPersistence assetCategoryPersistence;
    @BeanReference(type = com.liferay.portlet.asset.service.AssetEntryLocalService.class)
    protected com.liferay.portlet.asset.service.AssetEntryLocalService assetEntryLocalService;
    @BeanReference(type = com.liferay.portlet.asset.service.AssetEntryService.class)
    protected com.liferay.portlet.asset.service.AssetEntryService assetEntryService;
    @BeanReference(type = AssetEntryPersistence.class)
    protected AssetEntryPersistence assetEntryPersistence;
    @BeanReference(type = com.liferay.portlet.asset.service.AssetLinkLocalService.class)
    protected com.liferay.portlet.asset.service.AssetLinkLocalService assetLinkLocalService;
    @BeanReference(type = AssetLinkPersistence.class)
    protected AssetLinkPersistence assetLinkPersistence;
    @BeanReference(type = com.liferay.portlet.asset.service.AssetTagLocalService.class)
    protected com.liferay.portlet.asset.service.AssetTagLocalService assetTagLocalService;
    @BeanReference(type = com.liferay.portlet.asset.service.AssetTagService.class)
    protected com.liferay.portlet.asset.service.AssetTagService assetTagService;
    @BeanReference(type = AssetTagPersistence.class)
    protected AssetTagPersistence assetTagPersistence;
    @BeanReference(type = com.liferay.portlet.dynamicdatamapping.service.DDMStructureLocalService.class)
    protected com.liferay.portlet.dynamicdatamapping.service.DDMStructureLocalService ddmStructureLocalService;
    @BeanReference(type = com.liferay.portlet.dynamicdatamapping.service.DDMStructureService.class)
    protected com.liferay.portlet.dynamicdatamapping.service.DDMStructureService ddmStructureService;
    @BeanReference(type = DDMStructurePersistence.class)
    protected DDMStructurePersistence ddmStructurePersistence;
    @BeanReference(type = com.liferay.portlet.dynamicdatamapping.service.DDMTemplateLocalService.class)
    protected com.liferay.portlet.dynamicdatamapping.service.DDMTemplateLocalService ddmTemplateLocalService;
    @BeanReference(type = com.liferay.portlet.dynamicdatamapping.service.DDMTemplateService.class)
    protected com.liferay.portlet.dynamicdatamapping.service.DDMTemplateService ddmTemplateService;
    @BeanReference(type = DDMTemplatePersistence.class)
    protected DDMTemplatePersistence ddmTemplatePersistence;
    @BeanReference(type = com.liferay.portlet.ratings.service.RatingsStatsLocalService.class)
    protected com.liferay.portlet.ratings.service.RatingsStatsLocalService ratingsStatsLocalService;
    @BeanReference(type = RatingsStatsPersistence.class)
    protected RatingsStatsPersistence ratingsStatsPersistence;
    @BeanReference(type = com.liferay.portlet.social.service.SocialActivityLocalService.class)
    protected com.liferay.portlet.social.service.SocialActivityLocalService socialActivityLocalService;
    @BeanReference(type = com.liferay.portlet.social.service.SocialActivityService.class)
    protected com.liferay.portlet.social.service.SocialActivityService socialActivityService;
    @BeanReference(type = SocialActivityPersistence.class)
    protected SocialActivityPersistence socialActivityPersistence;
    @BeanReference(type = com.liferay.portlet.social.service.SocialActivityCounterLocalService.class)
    protected com.liferay.portlet.social.service.SocialActivityCounterLocalService socialActivityCounterLocalService;
    @BeanReference(type = SocialActivityCounterPersistence.class)
    protected SocialActivityCounterPersistence socialActivityCounterPersistence;
    @BeanReference(type = com.liferay.portlet.trash.service.TrashEntryLocalService.class)
    protected com.liferay.portlet.trash.service.TrashEntryLocalService trashEntryLocalService;
    @BeanReference(type = com.liferay.portlet.trash.service.TrashEntryService.class)
    protected com.liferay.portlet.trash.service.TrashEntryService trashEntryService;
    @BeanReference(type = TrashEntryPersistence.class)
    protected TrashEntryPersistence trashEntryPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private PublicationServiceClpInvoker _clpInvoker = new PublicationServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link fr.lagab.portlet.publication.service.PublicationServiceUtil} to access the publication remote service.
     */

    /**
     * Returns the publication local service.
     *
     * @return the publication local service
     */
    public fr.lagab.portlet.publication.service.PublicationLocalService getPublicationLocalService() {
        return publicationLocalService;
    }

    /**
     * Sets the publication local service.
     *
     * @param publicationLocalService the publication local service
     */
    public void setPublicationLocalService(
        fr.lagab.portlet.publication.service.PublicationLocalService publicationLocalService) {
        this.publicationLocalService = publicationLocalService;
    }

    /**
     * Returns the publication remote service.
     *
     * @return the publication remote service
     */
    public fr.lagab.portlet.publication.service.PublicationService getPublicationService() {
        return publicationService;
    }

    /**
     * Sets the publication remote service.
     *
     * @param publicationService the publication remote service
     */
    public void setPublicationService(
        fr.lagab.portlet.publication.service.PublicationService publicationService) {
        this.publicationService = publicationService;
    }

    /**
     * Returns the publication persistence.
     *
     * @return the publication persistence
     */
    public PublicationPersistence getPublicationPersistence() {
        return publicationPersistence;
    }

    /**
     * Sets the publication persistence.
     *
     * @param publicationPersistence the publication persistence
     */
    public void setPublicationPersistence(
        PublicationPersistence publicationPersistence) {
        this.publicationPersistence = publicationPersistence;
    }

    /**
     * Returns the publication structure local service.
     *
     * @return the publication structure local service
     */
    @SuppressWarnings("deprecation")
    public fr.lagab.portlet.publication.service.PublicationStructureLocalService getPublicationStructureLocalService() {
        return publicationStructureLocalService;
    }

    /**
     * Sets the publication structure local service.
     *
     * @param publicationStructureLocalService the publication structure local service
     */
    @SuppressWarnings("deprecation")
    public void setPublicationStructureLocalService(
        fr.lagab.portlet.publication.service.PublicationStructureLocalService publicationStructureLocalService) {
        this.publicationStructureLocalService = publicationStructureLocalService;
    }

    /**
     * Returns the publication structure remote service.
     *
     * @return the publication structure remote service
     */
    @SuppressWarnings("deprecation")
    public fr.lagab.portlet.publication.service.PublicationStructureService getPublicationStructureService() {
        return publicationStructureService;
    }

    /**
     * Sets the publication structure remote service.
     *
     * @param publicationStructureService the publication structure remote service
     */
    @SuppressWarnings("deprecation")
    public void setPublicationStructureService(
        fr.lagab.portlet.publication.service.PublicationStructureService publicationStructureService) {
        this.publicationStructureService = publicationStructureService;
    }

    /**
     * Returns the publication template local service.
     *
     * @return the publication template local service
     */
    @SuppressWarnings("deprecation")
    public fr.lagab.portlet.publication.service.PublicationTemplateLocalService getPublicationTemplateLocalService() {
        return publicationTemplateLocalService;
    }

    /**
     * Sets the publication template local service.
     *
     * @param publicationTemplateLocalService the publication template local service
     */
    @SuppressWarnings("deprecation")
    public void setPublicationTemplateLocalService(
        fr.lagab.portlet.publication.service.PublicationTemplateLocalService publicationTemplateLocalService) {
        this.publicationTemplateLocalService = publicationTemplateLocalService;
    }

    /**
     * Returns the publication template remote service.
     *
     * @return the publication template remote service
     */
    @SuppressWarnings("deprecation")
    public fr.lagab.portlet.publication.service.PublicationTemplateService getPublicationTemplateService() {
        return publicationTemplateService;
    }

    /**
     * Sets the publication template remote service.
     *
     * @param publicationTemplateService the publication template remote service
     */
    @SuppressWarnings("deprecation")
    public void setPublicationTemplateService(
        fr.lagab.portlet.publication.service.PublicationTemplateService publicationTemplateService) {
        this.publicationTemplateService = publicationTemplateService;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the mail remote service.
     *
     * @return the mail remote service
     */
    public com.liferay.mail.service.MailService getMailService() {
        return mailService;
    }

    /**
     * Sets the mail remote service.
     *
     * @param mailService the mail remote service
     */
    public void setMailService(com.liferay.mail.service.MailService mailService) {
        this.mailService = mailService;
    }

    /**
     * Returns the company local service.
     *
     * @return the company local service
     */
    public com.liferay.portal.service.CompanyLocalService getCompanyLocalService() {
        return companyLocalService;
    }

    /**
     * Sets the company local service.
     *
     * @param companyLocalService the company local service
     */
    public void setCompanyLocalService(
        com.liferay.portal.service.CompanyLocalService companyLocalService) {
        this.companyLocalService = companyLocalService;
    }

    /**
     * Returns the company remote service.
     *
     * @return the company remote service
     */
    public com.liferay.portal.service.CompanyService getCompanyService() {
        return companyService;
    }

    /**
     * Sets the company remote service.
     *
     * @param companyService the company remote service
     */
    public void setCompanyService(
        com.liferay.portal.service.CompanyService companyService) {
        this.companyService = companyService;
    }

    /**
     * Returns the company persistence.
     *
     * @return the company persistence
     */
    public CompanyPersistence getCompanyPersistence() {
        return companyPersistence;
    }

    /**
     * Sets the company persistence.
     *
     * @param companyPersistence the company persistence
     */
    public void setCompanyPersistence(CompanyPersistence companyPersistence) {
        this.companyPersistence = companyPersistence;
    }

    /**
     * Returns the group local service.
     *
     * @return the group local service
     */
    public com.liferay.portal.service.GroupLocalService getGroupLocalService() {
        return groupLocalService;
    }

    /**
     * Sets the group local service.
     *
     * @param groupLocalService the group local service
     */
    public void setGroupLocalService(
        com.liferay.portal.service.GroupLocalService groupLocalService) {
        this.groupLocalService = groupLocalService;
    }

    /**
     * Returns the group remote service.
     *
     * @return the group remote service
     */
    public com.liferay.portal.service.GroupService getGroupService() {
        return groupService;
    }

    /**
     * Sets the group remote service.
     *
     * @param groupService the group remote service
     */
    public void setGroupService(
        com.liferay.portal.service.GroupService groupService) {
        this.groupService = groupService;
    }

    /**
     * Returns the group persistence.
     *
     * @return the group persistence
     */
    public GroupPersistence getGroupPersistence() {
        return groupPersistence;
    }

    /**
     * Sets the group persistence.
     *
     * @param groupPersistence the group persistence
     */
    public void setGroupPersistence(GroupPersistence groupPersistence) {
        this.groupPersistence = groupPersistence;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    /**
     * Returns the asset category local service.
     *
     * @return the asset category local service
     */
    public com.liferay.portlet.asset.service.AssetCategoryLocalService getAssetCategoryLocalService() {
        return assetCategoryLocalService;
    }

    /**
     * Sets the asset category local service.
     *
     * @param assetCategoryLocalService the asset category local service
     */
    public void setAssetCategoryLocalService(
        com.liferay.portlet.asset.service.AssetCategoryLocalService assetCategoryLocalService) {
        this.assetCategoryLocalService = assetCategoryLocalService;
    }

    /**
     * Returns the asset category remote service.
     *
     * @return the asset category remote service
     */
    public com.liferay.portlet.asset.service.AssetCategoryService getAssetCategoryService() {
        return assetCategoryService;
    }

    /**
     * Sets the asset category remote service.
     *
     * @param assetCategoryService the asset category remote service
     */
    public void setAssetCategoryService(
        com.liferay.portlet.asset.service.AssetCategoryService assetCategoryService) {
        this.assetCategoryService = assetCategoryService;
    }

    /**
     * Returns the asset category persistence.
     *
     * @return the asset category persistence
     */
    public AssetCategoryPersistence getAssetCategoryPersistence() {
        return assetCategoryPersistence;
    }

    /**
     * Sets the asset category persistence.
     *
     * @param assetCategoryPersistence the asset category persistence
     */
    public void setAssetCategoryPersistence(
        AssetCategoryPersistence assetCategoryPersistence) {
        this.assetCategoryPersistence = assetCategoryPersistence;
    }

    /**
     * Returns the asset entry local service.
     *
     * @return the asset entry local service
     */
    public com.liferay.portlet.asset.service.AssetEntryLocalService getAssetEntryLocalService() {
        return assetEntryLocalService;
    }

    /**
     * Sets the asset entry local service.
     *
     * @param assetEntryLocalService the asset entry local service
     */
    public void setAssetEntryLocalService(
        com.liferay.portlet.asset.service.AssetEntryLocalService assetEntryLocalService) {
        this.assetEntryLocalService = assetEntryLocalService;
    }

    /**
     * Returns the asset entry remote service.
     *
     * @return the asset entry remote service
     */
    public com.liferay.portlet.asset.service.AssetEntryService getAssetEntryService() {
        return assetEntryService;
    }

    /**
     * Sets the asset entry remote service.
     *
     * @param assetEntryService the asset entry remote service
     */
    public void setAssetEntryService(
        com.liferay.portlet.asset.service.AssetEntryService assetEntryService) {
        this.assetEntryService = assetEntryService;
    }

    /**
     * Returns the asset entry persistence.
     *
     * @return the asset entry persistence
     */
    public AssetEntryPersistence getAssetEntryPersistence() {
        return assetEntryPersistence;
    }

    /**
     * Sets the asset entry persistence.
     *
     * @param assetEntryPersistence the asset entry persistence
     */
    public void setAssetEntryPersistence(
        AssetEntryPersistence assetEntryPersistence) {
        this.assetEntryPersistence = assetEntryPersistence;
    }

    /**
     * Returns the asset link local service.
     *
     * @return the asset link local service
     */
    public com.liferay.portlet.asset.service.AssetLinkLocalService getAssetLinkLocalService() {
        return assetLinkLocalService;
    }

    /**
     * Sets the asset link local service.
     *
     * @param assetLinkLocalService the asset link local service
     */
    public void setAssetLinkLocalService(
        com.liferay.portlet.asset.service.AssetLinkLocalService assetLinkLocalService) {
        this.assetLinkLocalService = assetLinkLocalService;
    }

    /**
     * Returns the asset link persistence.
     *
     * @return the asset link persistence
     */
    public AssetLinkPersistence getAssetLinkPersistence() {
        return assetLinkPersistence;
    }

    /**
     * Sets the asset link persistence.
     *
     * @param assetLinkPersistence the asset link persistence
     */
    public void setAssetLinkPersistence(
        AssetLinkPersistence assetLinkPersistence) {
        this.assetLinkPersistence = assetLinkPersistence;
    }

    /**
     * Returns the asset tag local service.
     *
     * @return the asset tag local service
     */
    public com.liferay.portlet.asset.service.AssetTagLocalService getAssetTagLocalService() {
        return assetTagLocalService;
    }

    /**
     * Sets the asset tag local service.
     *
     * @param assetTagLocalService the asset tag local service
     */
    public void setAssetTagLocalService(
        com.liferay.portlet.asset.service.AssetTagLocalService assetTagLocalService) {
        this.assetTagLocalService = assetTagLocalService;
    }

    /**
     * Returns the asset tag remote service.
     *
     * @return the asset tag remote service
     */
    public com.liferay.portlet.asset.service.AssetTagService getAssetTagService() {
        return assetTagService;
    }

    /**
     * Sets the asset tag remote service.
     *
     * @param assetTagService the asset tag remote service
     */
    public void setAssetTagService(
        com.liferay.portlet.asset.service.AssetTagService assetTagService) {
        this.assetTagService = assetTagService;
    }

    /**
     * Returns the asset tag persistence.
     *
     * @return the asset tag persistence
     */
    public AssetTagPersistence getAssetTagPersistence() {
        return assetTagPersistence;
    }

    /**
     * Sets the asset tag persistence.
     *
     * @param assetTagPersistence the asset tag persistence
     */
    public void setAssetTagPersistence(AssetTagPersistence assetTagPersistence) {
        this.assetTagPersistence = assetTagPersistence;
    }

    /**
     * Returns the d d m structure local service.
     *
     * @return the d d m structure local service
     */
    public com.liferay.portlet.dynamicdatamapping.service.DDMStructureLocalService getDDMStructureLocalService() {
        return ddmStructureLocalService;
    }

    /**
     * Sets the d d m structure local service.
     *
     * @param ddmStructureLocalService the d d m structure local service
     */
    public void setDDMStructureLocalService(
        com.liferay.portlet.dynamicdatamapping.service.DDMStructureLocalService ddmStructureLocalService) {
        this.ddmStructureLocalService = ddmStructureLocalService;
    }

    /**
     * Returns the d d m structure remote service.
     *
     * @return the d d m structure remote service
     */
    public com.liferay.portlet.dynamicdatamapping.service.DDMStructureService getDDMStructureService() {
        return ddmStructureService;
    }

    /**
     * Sets the d d m structure remote service.
     *
     * @param ddmStructureService the d d m structure remote service
     */
    public void setDDMStructureService(
        com.liferay.portlet.dynamicdatamapping.service.DDMStructureService ddmStructureService) {
        this.ddmStructureService = ddmStructureService;
    }

    /**
     * Returns the d d m structure persistence.
     *
     * @return the d d m structure persistence
     */
    public DDMStructurePersistence getDDMStructurePersistence() {
        return ddmStructurePersistence;
    }

    /**
     * Sets the d d m structure persistence.
     *
     * @param ddmStructurePersistence the d d m structure persistence
     */
    public void setDDMStructurePersistence(
        DDMStructurePersistence ddmStructurePersistence) {
        this.ddmStructurePersistence = ddmStructurePersistence;
    }

    /**
     * Returns the d d m template local service.
     *
     * @return the d d m template local service
     */
    public com.liferay.portlet.dynamicdatamapping.service.DDMTemplateLocalService getDDMTemplateLocalService() {
        return ddmTemplateLocalService;
    }

    /**
     * Sets the d d m template local service.
     *
     * @param ddmTemplateLocalService the d d m template local service
     */
    public void setDDMTemplateLocalService(
        com.liferay.portlet.dynamicdatamapping.service.DDMTemplateLocalService ddmTemplateLocalService) {
        this.ddmTemplateLocalService = ddmTemplateLocalService;
    }

    /**
     * Returns the d d m template remote service.
     *
     * @return the d d m template remote service
     */
    public com.liferay.portlet.dynamicdatamapping.service.DDMTemplateService getDDMTemplateService() {
        return ddmTemplateService;
    }

    /**
     * Sets the d d m template remote service.
     *
     * @param ddmTemplateService the d d m template remote service
     */
    public void setDDMTemplateService(
        com.liferay.portlet.dynamicdatamapping.service.DDMTemplateService ddmTemplateService) {
        this.ddmTemplateService = ddmTemplateService;
    }

    /**
     * Returns the d d m template persistence.
     *
     * @return the d d m template persistence
     */
    public DDMTemplatePersistence getDDMTemplatePersistence() {
        return ddmTemplatePersistence;
    }

    /**
     * Sets the d d m template persistence.
     *
     * @param ddmTemplatePersistence the d d m template persistence
     */
    public void setDDMTemplatePersistence(
        DDMTemplatePersistence ddmTemplatePersistence) {
        this.ddmTemplatePersistence = ddmTemplatePersistence;
    }

    /**
     * Returns the ratings stats local service.
     *
     * @return the ratings stats local service
     */
    public com.liferay.portlet.ratings.service.RatingsStatsLocalService getRatingsStatsLocalService() {
        return ratingsStatsLocalService;
    }

    /**
     * Sets the ratings stats local service.
     *
     * @param ratingsStatsLocalService the ratings stats local service
     */
    public void setRatingsStatsLocalService(
        com.liferay.portlet.ratings.service.RatingsStatsLocalService ratingsStatsLocalService) {
        this.ratingsStatsLocalService = ratingsStatsLocalService;
    }

    /**
     * Returns the ratings stats persistence.
     *
     * @return the ratings stats persistence
     */
    public RatingsStatsPersistence getRatingsStatsPersistence() {
        return ratingsStatsPersistence;
    }

    /**
     * Sets the ratings stats persistence.
     *
     * @param ratingsStatsPersistence the ratings stats persistence
     */
    public void setRatingsStatsPersistence(
        RatingsStatsPersistence ratingsStatsPersistence) {
        this.ratingsStatsPersistence = ratingsStatsPersistence;
    }

    /**
     * Returns the social activity local service.
     *
     * @return the social activity local service
     */
    public com.liferay.portlet.social.service.SocialActivityLocalService getSocialActivityLocalService() {
        return socialActivityLocalService;
    }

    /**
     * Sets the social activity local service.
     *
     * @param socialActivityLocalService the social activity local service
     */
    public void setSocialActivityLocalService(
        com.liferay.portlet.social.service.SocialActivityLocalService socialActivityLocalService) {
        this.socialActivityLocalService = socialActivityLocalService;
    }

    /**
     * Returns the social activity remote service.
     *
     * @return the social activity remote service
     */
    public com.liferay.portlet.social.service.SocialActivityService getSocialActivityService() {
        return socialActivityService;
    }

    /**
     * Sets the social activity remote service.
     *
     * @param socialActivityService the social activity remote service
     */
    public void setSocialActivityService(
        com.liferay.portlet.social.service.SocialActivityService socialActivityService) {
        this.socialActivityService = socialActivityService;
    }

    /**
     * Returns the social activity persistence.
     *
     * @return the social activity persistence
     */
    public SocialActivityPersistence getSocialActivityPersistence() {
        return socialActivityPersistence;
    }

    /**
     * Sets the social activity persistence.
     *
     * @param socialActivityPersistence the social activity persistence
     */
    public void setSocialActivityPersistence(
        SocialActivityPersistence socialActivityPersistence) {
        this.socialActivityPersistence = socialActivityPersistence;
    }

    /**
     * Returns the social activity counter local service.
     *
     * @return the social activity counter local service
     */
    public com.liferay.portlet.social.service.SocialActivityCounterLocalService getSocialActivityCounterLocalService() {
        return socialActivityCounterLocalService;
    }

    /**
     * Sets the social activity counter local service.
     *
     * @param socialActivityCounterLocalService the social activity counter local service
     */
    public void setSocialActivityCounterLocalService(
        com.liferay.portlet.social.service.SocialActivityCounterLocalService socialActivityCounterLocalService) {
        this.socialActivityCounterLocalService = socialActivityCounterLocalService;
    }

    /**
     * Returns the social activity counter persistence.
     *
     * @return the social activity counter persistence
     */
    public SocialActivityCounterPersistence getSocialActivityCounterPersistence() {
        return socialActivityCounterPersistence;
    }

    /**
     * Sets the social activity counter persistence.
     *
     * @param socialActivityCounterPersistence the social activity counter persistence
     */
    public void setSocialActivityCounterPersistence(
        SocialActivityCounterPersistence socialActivityCounterPersistence) {
        this.socialActivityCounterPersistence = socialActivityCounterPersistence;
    }

    /**
     * Returns the trash entry local service.
     *
     * @return the trash entry local service
     */
    public com.liferay.portlet.trash.service.TrashEntryLocalService getTrashEntryLocalService() {
        return trashEntryLocalService;
    }

    /**
     * Sets the trash entry local service.
     *
     * @param trashEntryLocalService the trash entry local service
     */
    public void setTrashEntryLocalService(
        com.liferay.portlet.trash.service.TrashEntryLocalService trashEntryLocalService) {
        this.trashEntryLocalService = trashEntryLocalService;
    }

    /**
     * Returns the trash entry remote service.
     *
     * @return the trash entry remote service
     */
    public com.liferay.portlet.trash.service.TrashEntryService getTrashEntryService() {
        return trashEntryService;
    }

    /**
     * Sets the trash entry remote service.
     *
     * @param trashEntryService the trash entry remote service
     */
    public void setTrashEntryService(
        com.liferay.portlet.trash.service.TrashEntryService trashEntryService) {
        this.trashEntryService = trashEntryService;
    }

    /**
     * Returns the trash entry persistence.
     *
     * @return the trash entry persistence
     */
    public TrashEntryPersistence getTrashEntryPersistence() {
        return trashEntryPersistence;
    }

    /**
     * Sets the trash entry persistence.
     *
     * @param trashEntryPersistence the trash entry persistence
     */
    public void setTrashEntryPersistence(
        TrashEntryPersistence trashEntryPersistence) {
        this.trashEntryPersistence = trashEntryPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Publication.class;
    }

    protected String getModelClassName() {
        return Publication.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = publicationPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
